# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\USER\Documents\Code\Code\oke.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cover(object):
    def setupUi(self, cover):
        cover.setObjectName("cover")
        cover.resize(1305, 952)
        self.centralwidget = QtWidgets.QWidget(cover)
        self.centralwidget.setObjectName("centralwidget")
        self.mulai = QtWidgets.QPushButton(self.centralwidget)
        self.mulai.setGeometry(QtCore.QRect(290, 260, 621, 241))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.mulai.setFont(font)
        self.mulai.setStyleSheet("\n"
"border-radius: 30px")
        self.mulai.setText("")
        self.mulai.setObjectName("mulai")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1221, 746))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("border-image: url(:/Background/background.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\USER\\Documents\\Code\\Code\\background.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 260, 611, 241))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\USER\\Documents\\Code\\Code\\JUDUL.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 460, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(870, 420, 421, 421))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("c:\\Users\\USER\\Documents\\Code\\Code\\jambu.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label.raise_()
        self.label_2.raise_()
        self.mulai.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        cover.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cover)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1305, 26))
        self.menubar.setObjectName("menubar")
        cover.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cover)
        self.statusbar.setObjectName("statusbar")
        cover.setStatusBar(self.statusbar)

        self.retranslateUi(cover)
        QtCore.QMetaObject.connectSlotsByName(cover)

    def retranslateUi(self, cover):
        _translate = QtCore.QCoreApplication.translate
        cover.setWindowTitle(_translate("cover", "MainWindow"))
        self.label_3.setText(_translate("cover", "Guava Analyze Klik Disini Untuk Melanjutakan"))
import background_rc
